# Generated by Django 5.0.1 on 2024-01-16 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='makeup_images/')),
            ],
        ),
        migrations.CreateModel(
            name='MakeupService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('images', models.ManyToManyField(related_name='makeup_services', to='Services.image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='makeup_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.makeupservice'),
        ),
    ]
