# Generated by Django 5.0.1 on 2024-01-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeupservice',
            name='images',
        ),
        migrations.AddField(
            model_name='makeupservice',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='makeup_images/'),
        ),
        migrations.AddField(
            model_name='makeupservice',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='makeup_images/'),
        ),
        migrations.AddField(
            model_name='makeupservice',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='makeup_images/'),
        ),
    ]
