# Generated by Django 5.0.1 on 2024-01-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_remove_makeupservice_images_makeupservice_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeupservice',
            name='ville',
            field=models.CharField(default='', max_length=50),
        ),
    ]
