# Generated by Django 5.0.1 on 2024-01-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_makeupservice_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeupservice',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
