# Generated by Django 5.0.1 on 2024-01-17 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_makeupservice_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('makeup_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Services.makeupservice')),
            ],
        ),
    ]
