# Generated by Django 5.0.1 on 2024-01-19 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_djsservices_imagedjs_ratingdjs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatererService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='caterer_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='caterer_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='caterer_images/')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('ville', models.CharField(default='', max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('price_per_Table', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='caterer_images/')),
                ('caterer_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.catererservice')),
            ],
        ),
        migrations.CreateModel(
            name='RatingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('caterer_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Services.catererservice')),
            ],
        ),
    ]
