# Generated by Django 5.0.1 on 2024-01-11 16:01

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=10, prefix='', unique=True)),
                ('NomClient', models.CharField(max_length=100)),
                ('EmailC', models.CharField(max_length=100)),
                ('TypeMar', models.CharField(max_length=100)),
                ('Comment', models.CharField(max_length=250)),
                ('dateApp', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
