# Generated by Django 5.0.1 on 2024-01-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoi',
            name='EmailC',
            field=models.EmailField(max_length=100),
        ),
    ]
